apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qby4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qby4
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qby4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qby4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qby4
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pdka-tenant/rhtap-demo-app/hacbs-test-project-qby4@sha256:1166717653c9d645ce62a3a7fe3434875f626c8f0d7f7509e0135b1a5d7b7b11
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
