apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qby4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pdka-tenant/rhtap-demo-app/hacbs-test-project-qby4@sha256:1166717653c9d645ce62a3a7fe3434875f626c8f0d7f7509e0135b1a5d7b7b11
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
